FROM node:20.18-alpine

WORKDIR /app

# 의존성 파일 복사 및 설치
COPY package*.json ./
RUN npm install

# 애플리케이션 소스 코드 복사
COPY . .

# 빌드
RUN npm run build
RUN npm install -g http-server

EXPOSE 8080

CMD [ "http-server", "dist" ]
